### ISSUE TITLE
Cannot Install  Error Install Module

### ISSUE THREAD

**Issue by enazman** [webkul/hotelcommerce#41]
Installation process stop at 67% Install module 

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

![image](https://user-images.githubusercontent.com/32297555/37243787-1acc6388-24ba-11e8-8517-61b86b51dfdb.png)

**Comment by sumitwebkul** [comment]
Hi,
Increase variables values ,
max_execution_time = 500
upload_max_filesize = 16M in your php.ini file and restart your server once.

Please replace the attached files in the hotelcommerce folder on your server also. Path of the files are as follows-
**hotelcommerce/modules/hotelreservationsystem/classes/HotelBookingDetail.php**
**hotelcommerce/modules/hotelreservationsystem/classes/HotelBranchInformation.php**
 Please also visit https://qloapps.com/install-qloapps/ for installation help.
Try installing after these changes. In case issue persists then we recommend you to raise a ticket at https://webkul.uvdesk.com/ with your ftp details and the url on which you are installing Qloapps. We will resolve your issue there.
[InstallFiles.zip](https://github.com/webkul/hotelcommerce/files/1810080/InstallFiles.zip)

**Comment by enazman** [comment]
Thank you. Problem solved by increase the cariables. tq.

**Comment by betamaxtelecom** [comment]
Hello problem is fixed with php 5.4 and install files.zip 

Thanks

**Comment by delete-this-account** [comment]
Faced error with first install and theses setting:
```
PHP Version 5.4.31
upload_max_filesize=2000M
max_execution_time=500
memory_limit=512M
Simplexml support	enabled
Soap Client 	enabled
Soap Server 	enabled 
cURL support 	enabled 
```

Did not fix the 67% error on Install modules as the OP screen shot.
But the zip file and replace the 2 files fixed the same issue with me.

Thank you.

**Comment by sumitwebkul** [comment]
Ok,
We will fix it in the next updated version.
Thanks

**Comment by umarbashirdar** [comment]
@sumitwebkul   
It moved beyond that point. But after installation completes, i click on the "Manage you store" (Back office) and it redirects me to this URL

http://localhost:8080/hotelcom/admin620ejp6wd/index.php?controller=AdminLogin&token=05fb21ead6fd4c63cfb489c99bb79ba8

It display an empty page.

However, i am able to "View Front office" by clicking on "Discover your store".

To be precise, i am unable to view the admin part, it shows an empty page.
 Is there any fix to the problem?

**Comment by sumitwebkul** [comment]
@umarbashirdar 
Please open file "hotelcommerce/config/defines.inc.php" .
Here at **line 29** you will find below code - 
**define('_PS_MODE_DEV_', false);**
Please replace this code with the following code
**define('_PS_MODE_DEV_', true);**
Then reload the backoffice page again.
Please let me know what issue is occuring on the page.
Thanks

**Comment by umarbashirdar** [comment]
@sumitwebkul 

Here is the error i get now

Deprecated: Function mcrypt_decrypt() is deprecated in C:\xampp\htdocs\hotelcom\classes\Rijndael.php on line 68

Fatal error: Redefinition of parameter $id_shop in C:\xampp\htdocs\hotelcom\classes\module\Module.php(1362) : eval()'d code on line 797

**Comment by sumitwebkul** [comment]
@umarbashirdar 
We are not getting such issue at our end. We have to check this issue on your server.
But you are working on localhost. So we can't access your server. If you are able to create a public server then try to install Qloapps on it and provide us details of Admin Login credentials and FTP details of that server.
If you are unable to do that. Then it may be issue occurred on installation process.
We recommend you to use php higher version like php5.6 on your server and then try installing a fresh copy of Qloapps.
Please visit https://qloapps.com/install-qloapps/ for the environment set for the Qloapps properly.
If issue persists the let me know.

**Comment by umarbashirdar** [comment]
@sumitwebkul  please comment your email address.
I will share the FTP credentials with you.

**Comment by sumitwebkul** [comment]
Please raise a ticket at https://webkul.uvdesk.com/ with your ftp details and admin login credentials. We will resolve your issue there.
Thanks.

**Comment by wdammak** [comment]
to close
